# Environment-specific variables for dev
# Generated by Backstage for cluster: nikhil-test

# Cluster configuration
cluster_name = "nikhil-test"
aws_region = "us-east-1"
environment = "dev"

# Networking
vpc_id = "vpc-07a2436391cb04af5"
cluster_security_group_id = "sg-0e3a8301268c0514f"

# Capacity configuration
on_demand_instance_type = "t3.medium"
on_demand_min_size = 1
on_demand_max_size = 10
on_demand_desired_capacity = 1

# Monitoring
enable_container_insights = true

# Add any additional environment-specific overrides below
# Example:
# log_retention_period = 30
# target_capacity = 90
