# Environment-specific variables for dev
# Generated by Backstage for cluster: nikhil-test

# These values override the defaults in variables.tf
# Modify as needed for your environment

# Cluster configuration (already set by template)
# cluster_name = "nikhil-test"
# aws_region = "us-east-1"
# environment = "dev"

# Networking (required - update with your actual values)
# vpc_id = "vpc-123456"
# cluster_security_group_id = "sg-123456"

# Capacity configuration
# on_demand_instance_type = "t3.medium"
# on_demand_min_size = 1
# on_demand_max_size = 10
# on_demand_desired_capacity = 1

# Monitoring
# enable_container_insights = true

# Add any additional environment-specific overrides below
# Example:
# log_retention_period = 30
# target_capacity = 90
